### ISSUE TITLE
Create a v4 set

### ISSUE THREAD

**Issue by jsumners** [fastify/workflows#106]
A new `v4` tag should be create that points to a set of workflows that drop Node.js <=16. Any changes to `v3` should happen on the https://github.com/fastify/workflows/tree/v3.y.z branch.

**Comment by nrayburn-tech** [comment]
If outside contributors are welcome for this, I can make a PR for it.

Should the PR target `main`, or should a v4 branch be created first?
Is it possible to test the changes before putting up a PR?  (Maybe in combination with the PR I'm going to make for https://github.com/fastify/fast-content-type-parse/issues/20?)

**Comment by jsumners** [comment]
@nrayburn-tech you are welcome to take this on. For this, you can target the `main` branch.

The only real way to test these things is to publish them and use them in a project. So once we have a new v4 tag on `main`, a repo can reference it in a new PR and that PR's CI will use it. We don't need to worry about churn on the v4 tag if issues pop up. Nothing should be using it except for the PR(s) referencing it.
