### ISSUE TITLE
Either a v4 tag or branch should be created or the README should be updated

### ISSUE THREAD

**Issue by 10xLaCroixDrinker** [fastify/workflows#123]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The README says to use `@v4`, but this does not exist.

```yml
jobs:
  ci:
    uses: fastify/workflows/.github/workflows/plugins-ci.yml@v4
```

See this failing run on fastify-flash for reference

https://github.com/fastify/fastify-flash/actions/runs/7835351308/workflow

```
Check failure on line 20 in .github/workflows/ci.yml

GitHub Actions
/ .github/workflows/ci.yml
Invalid workflow file
error parsing called workflow
".github/workflows/ci.yml"
-> "fastify/workflows/.github/workflows/plugins-ci.yml@v4"
: failed to fetch workflow: reference to workflow should be either a valid branch, tag, or commit
```

**Comment by 10xLaCroixDrinker** [comment]
Thanks for the context @gurgunday. Would a PR to make the README reflect that be welcome?

**Comment by jsumners** [comment]
Time is better spent getting Fastify v5 ready and shipped, and/or fixing the dependabot problem. It _should not_ automatically update workflows with new major versions of this workflow.
