### ISSUE TITLE
package.json version on main

### ISSUE THREAD

**Issue by gurgunday** [fastify/workflows#125]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

For workflows we only do releases, but [we haven't so far touched the version on `package.json` and it still shows the version as `3` instead of `4`](https://github.com/fastify/workflows/blob/05d3c0bd5365e77b8e8acd3f61a42f44c4ad6aba/package.json#L3), in fact [it's even behind the `v3.y.z` branch](https://github.com/fastify/workflows/blob/758b570c189c8e178cf941104c39a2e618d1ee81/package.json#L3)

Should we update that before releasing `v4.2.0`? Note that the branch `v3.y.z` is where the 3 line lives

@Fdawgs

**Comment by gurgunday** [comment]
I actually don't know _why_ there is even a package.json here

**Comment by Fdawgs** [comment]
It should be updated when running the release workflow, it's just that the recent releases went out without running that:

https://github.com/fastify/workflows/blob/main/CONTRIBUTING.md#release-process

**Comment by gurgunday** [comment]
Oh I see, but it says if we do that `v4` will be created, which we don't want

**Comment by gurgunday** [comment]
Thanks!
