### ISSUE TITLE
Why is this published to npm?

### ISSUE THREAD

**Issue by jsumners** [fastify/workflows#32]
https://github.com/fastify/workflows/blob/b8ebfe1107e95528de85b24e9518357636b4dab3/package.json#L2

**Comment by Fdawgs** [comment]
See https://github.com/fastify/workflows/pull/13, it never actually gets published to npm though.
Could slap a `"private": true` into `package.json` just to make sure?

**Comment by Fdawgs** [comment]
It's cutting github releases, and keeping all the tags up to date. When `v3.1.3` is released it creates a tag for that and also moves the `v3.1` and `v3` tags up to that latest release.
