### ISSUE TITLE
Create v1 release

### ISSUE THREAD

**Issue by Fdawgs** [fastify/workflows#4]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

@Eomm, @simoneb, are you be able to advise on how you create both major and semantic versioning releases for [fastify/github-action-merge-dependabot](https://github.com/fastify/github-action-merge-dependabot) please? Is it automatic or are you manually moving the tags?
It would be great to implement a similar process here i.e. v1 and v1.x.x.

**Comment by simoneb** [comment]
Using this action https://github.com/nearform/optic-release-automation-action and turning on the sync-semver-tags option

**Comment by Fdawgs** [comment]
> Using this action https://github.com/nearform/optic-release-automation-action and turning on the sync-semver-tags option

Brilliant, thanks!
