### ISSUE TITLE
Activate license-check for all repos/projects?

### ISSUE THREAD

**Issue by Uzlopak** [fastify/workflows#49]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Should we activate license-check in all repos?

**Comment by Fdawgs** [comment]
Got all of them. There are a few PRs that are failing because the repos are depending on packages with unaccepted licenses.

**Comment by Uzlopak** [comment]
@Fdawgs 

All purple now. Was nice to do this in a concentrated action ;).
