### ISSUE TITLE
Add node 19 to testmatrix

### ISSUE THREAD

**Issue by Uzlopak** [fastify/workflows#73]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

We should also test for node19.

**Comment by climba03003** [comment]
I would against to add it at this point.
`node@19` active support only 2 months left and security support is 4 months left.

**Comment by Fdawgs** [comment]
Don't think it's worth it at this point, sorry @Uzlopak. Node 20 is turning up in 2 months,
Will add that when it appears!

**Comment by Uzlopak** [comment]
Allright. ;)
