### ISSUE TITLE
Add package manager CI workflow

### ISSUE THREAD

**Issue by Fdawgs** [fastify/workflows#77]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

See https://github.com/fastify/fastify/blob/main/.github/workflows/package-manager-ci.yml and https://github.com/fastify/skeleton/blob/master/.github/workflows/package-manager-ci.yml

### Motivation

Shared CI across all repos, don't have to update them all separately.

**Comment by Uzlopak** [comment]
I like this idea.
