### ISSUE TITLE
benchmark workflow broken

### ISSUE THREAD

**Issue by Uzlopak** [fastify/workflows#93]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

It seems that github.event.pull_request.head.repo.full_name is potentially incorrect. maybe it has to be github.event.pull_request.base.repo.full_name.

**Comment by Eomm** [comment]
There should be both fields:
https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request

**Comment by mweberxyz** [comment]
I believe I understand the issue, taking https://github.com/fastify/point-of-view/pull/408 as an example, the filtered pull_request payload is:

<img width="626" alt="CleanShot 2024-02-20 at 14 18 12@2x" src="https://github.com/fastify/workflows/assets/1062734/4674c60f-e4db-4c10-b60b-6d60825ebd75">

But 408 is merging from mweberxyz/point-of-view fork into fastify/point-of-view, so the second `actions/checkout@v4` should use the base instead.

@Uzlopak is that the gist of it?

**Comment by Uzlopak** [comment]
I think your assessment is right.
