### ISSUE TITLE
Ensure that blueoak licensed packages are detected

### ISSUE THREAD

**Issue by Uzlopak** [fastify/workflows#97]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

According to @gurgunday tap is using BlueOak License and the license checked does not detect it as no allowed. We have to investigate on why this fails.

**Comment by Uzlopak** [comment]
Yes. It seems there is a miss if it is a direct dependency?

**Comment by Fdawgs** [comment]
It's because tap is a dev dependency and the license check in here is only looking at production ones.
It caught it in https://github.com/fastify/fastify-static/actions/runs/6177304982/job/16768155505 because @gurgunday was updating a production dependency.

https://github.com/fastify/workflows/blob/3ae0b4bec5551ee1370bd06c7f67a6c8217156cd/.github/workflows/plugins-ci.yml#L66C26-L66C55

**Comment by Fdawgs** [comment]
@Uzlopak may no longer be an issue?

https://github.com/openjs-foundation/cross-project-council/issues/1170#issuecomment-1802733531

**Comment by mcollina** [comment]
Everything should be ok in 2/3 months or so. There is 60 days grace time, then the OpenJS Board would issue a statement.

**Comment by Uzlopak** [comment]
@Fdawgs 

In a meeting with @rginn regarding some other OpenJS related topic last week I asked her about blueoak. She also said, that it should resolve positive.

**Comment by jsumners** [comment]
"Should" and "are" are not equivalent. I am keeping an eye on the progress and will keep the task list updated. A major bump in `tap` after any v5 related release is an internal matter and will not necessitate another new major.

**Comment by voxpelli** [comment]
Maybe rename this issue as it was initially meant as a big report about blue oak (dev) dependencies not being found by the workflow but now seems to be about tracking Blue Oak's OSI approval 😌

Or maybe there's another issue tracking the OSI-approval? In that case this issue can be closed in favor of that one.

**Comment by Uzlopak** [comment]
Blue Oak is OSI approved

https://twitter.com/MylesBorins/status/1752018663698321758

**Comment by rginn** [comment]
The OpenJS Board of Directors still need to vote to approve the Blue Oak license for OpenJS-hosted projects. The vote will take place this week.
